### ISSUE TITLE
login with mobile

### ISSUE THREAD

**Issue by tomatoinaction** [thethink3r/Proxmox-remove-no-subscription-message#1]
Hey i just loggedin on my mobile and saw that there is still this notification. (also reproducable possible over devtools in chrome and using device emulator toolbar)

maybe you can fix this pls?

![image](https://github.com/thethink3r/Proxmox-remove-no-subscription-message/assets/44731882/cb77f430-67a8-463b-bb2b-24eb25068bf7)

![image](https://github.com/thethink3r/Proxmox-remove-no-subscription-message/assets/44731882/5463bbf8-b258-430e-8b87-786fc28727b6)

thanks

**Comment by thethink3r** [comment]
fixed by commit 34a3b1a

Use `apt install --reinstall pve-manager` after update `/etc/apt/apt.conf.d/pve-no-subscription-message`
